name: Deploy in DEV phase

on:
  push:
    branches:
      - DEV/**

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client and Rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y ssh-client rsync

    - name: Deploy, build and run Docker
      env:
        DEPLOY_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ vars.PATH }}
      run: |
        # Write the SSH key to a file
        echo "$DEPLOY_SSH_KEY" > deploy_key
        chmod 600 deploy_key

        # Use rsync to deploy the code to the server
        rsync -avz -e "ssh -i deploy_key -p $SERVER_PORT -o StrictHostKeyChecking=no" --exclude '.git' --exclude 'deploy_key' ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH

        # Execute the Python script on the server
        ssh -i deploy_key -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $DEPLOY_PATH &&
          docker compose down &&
          docker compose up -d --build "

        # Cleanup
        rm -f deploy_key
