name: Deploy and Execute on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy and Execute Script on Server
      env:
        DEPLOY_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ secrets.PATH }}
      run: |
        # Install SSH client
        sudo apt-get install -y ssh-client

        # Write the SSH key to a file
        echo "$DEPLOY_SSH_KEY" > deploy_key
        chmod 600 deploy_key

        # Use rsync to deploy the code to the server
        rsync -avz -e "ssh -i deploy_key -p $SERVER_PORT -o StrictHostKeyChecking=no" --exclude '.git' ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH

        # Execute the Python script on the server
        ssh -i deploy_key -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $DEPLOY_PATH && source mpu_env/bin/activate && pip install -r requirements.txt && python main.py"

        # Cleanup
        rm -f deploy_key
